### Q1. What are the benefits of the built-in array package, if any?
Arrays can contain multiple data items of the same type.
One can get the elements just by using the corresponding index.
Arrays don't cause memory overflow because they allocate memory in contiguous memory locations for all its elements. There is no need for extra memory.
### Q2. What are some of the array package's limitations?
The size of the array needs to be specified before allocation.

Since it has a static structure, the size of the array , once specified, cannot be changed.

Insertion and deletion are difficult and swapping and shifting operations are expensive.

### Q3. Describe the main differences between the array and numpy packages.
NumPy offers a large variety of numerical operations while the array does not.

Access or append operation in a numpy takes longer time than an array.

Numpy forms a tabular structure while the array does not.

### Q4. Explain the distinctions between the empty, ones, and zeros functions
An empty function does not carry any statement within its body. To write a function definition without any statement in python will give an error. This can be avoided if one uses the pass statement. It is a special dummy statement in Python.

Ones function returns a new array of given shape and data type, where the value of all the elements being 1.

Zeros function returns a new array of given shape and data type, where the common value of all elements is 0.

### Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?
The role of the callable argument is to execute the function over each coordinate and the output array. The function is called with N parameters, where N is the rank of shape. Each parameter represents the coordinates of the array along different axis.

### Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?
If a scalar is added to a numpy array, then all the elements inside that array will have that value added to them, irrespective of the shape and size of the array.

### Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?
Yes they can. In that case, the scalar-operation will be applied on each and every element in that array.

In [1]:
import numpy as np
arr=np.arange(10,70,10).reshape(2,3)

In [2]:
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [3]:
arr+=1
arr

array([[11, 21, 31],
       [41, 51, 61]])

In [4]:
arr*=5
arr

array([[ 55, 105, 155],
       [205, 255, 305]])

### Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?
numpy array can contain fixed-length strings. The dtype of such an array is the maximum length of any string present in the array.

Once set, it can store new string values having length not exceeding the maximum length at the time of the creation. If one tries to reallocate a string value having length greater than the maximum length of the existing elements, then it simply discards all the character values in the string beyond the maximum length and takes upto those that are under the threshold.

In [5]:
arr=np.array(["Jacko","Jill","Up","Down"])

In [6]:
arr[arr=="Jill"]="Hickory"

In [7]:
arr

array(['Jacko', 'Hicko', 'Up', 'Down'], dtype='<U5')

### Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?
The operation will be one-to-one operation applied to the corresponding elements sharing a common index.

The conditions are:

The data type both the arrays should be same.
Shape of both the arrays need to be same.
### Q10. What is the best way to use a Boolean array to mask another array?

In [8]:
bool = np.array([True,True,False,True,False,True])          
x = np.array([1,2,3,4,5,6])         
mask = np.ma.masked_where(x**2>19,bool)  
print(list(mask))

[True, True, False, True, masked, masked]


### Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.

In [9]:
#Using math module

import math
arr=np.arange(9)
print(arr)
avg=np.mean(arr)
N=len(arr)
sum=0
for i in arr:
    sum=sum+(i-avg)**2
SD=math.sqrt(sum/N)
print("Standard deviation : ",SD)

[0 1 2 3 4 5 6 7 8]
Standard deviation :  2.581988897471611


In [10]:
#Arithmetics
SD= (sum/N)**0.5
print("Standard deviation : ",SD)

Standard deviation :  2.581988897471611


In [11]:
#Using Numpy Array package

SD=np.std(arr)
print("Standard deviation : ",SD)

Standard deviation :  2.581988897471611


### 12. What is the dimensionality of a Boolean mask-generated array?
It will be same as that of the original non-masked array.

In [12]:
bool = np.array([True,True,False,True,False,True])          
x = np.array([1,2,3,4,5,6])         
mask = np.ma.masked_where(x**2>19,bool)  
print("Dimension of input array : ", x.ndim)
print("Dimension of masked array : ", mask.ndim)

Dimension of input array :  1
Dimension of masked array :  1
